# THIS FILE NOT SHOULD BE IN GITHUB REPOSITORY BUT 
# THIS FILE IS FOR LEARNING PURPOSES ONLY
global:
  keycloak:
    auth:
      adminPassword: admin123
    postgresql:
      enabled: true
      auth:
        username: keycloak
        password: keycloak123
        database: keycloak

  rabbitmq:
    auth:
      password: rabbitmq123


  redis:
    password: redis123
