{{- if and (eq (include "keycloak.enabled" .) "true") (include "keycloak.adminPassword" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
type: Opaque
stringData:
  KEYCLOAK_ADMIN_PASSWORD: {{ include "keycloak.adminPassword" . }}
{{- end }}
