apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-connection
data:
  KEYCLOAK_ADMIN_USER: {{ .Values.global.keycloak.auth.adminUser | quote }}
  KEYCLOAK_VENDOR: {{ .Values.global.keycloak.database.vendor | quote }}
  KEYCLOAK_HOSTNAME: {{ .Values.global.keycloak.database.hostname | quote }}
  KEYCLOAK_PORT: {{ .Values.global.keycloak.database.port | quote }}
  KEYCLOAK_DATABASE: {{ .Values.global.keycloak.database.database | quote }}
  KEYCLOAK_DB_USER: {{ .Values.global.keycloak.database.username | quote }}
