{{- if eq (include "keycloak.enabled" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-connection
data:
  KEYCLOAK_ADMIN_USER: {{ include "keycloak.adminUser" . }}
  KEYCLOAK_VENDOR: {{ include "keycloak.db.vendor" . }}
  KEYCLOAK_HOSTNAME: {{ include "keycloak.db.hostname" . }}
  KEYCLOAK_PORT: {{ include "keycloak.db.port" . }}
  KEYCLOAK_DATABASE: {{ include "keycloak.db.name" . }}
  KEYCLOAK_DB_USER: {{ include "keycloak.db.username" . }}
{{- end }}
