{{- if and .Values.global .Values.global.rabbitmq .Values.global.rabbitmq.auth .Values.global.rabbitmq.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
stringData:
  
  rabbitmq-password: {{ include "rabbitmq.password" . }}
  {{- end }}