
{{- if eq (include "rabbitmq.enabled" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-connection
data:
  RABBITMQ_HOST: {{ include "rabbitmq.host" . }}
  RABBITMQ_PORT: {{ include "rabbitmq.port" . }}
  RABBITMQ_USERNAME: {{ include "rabbitmq.username" . }}
{{- end }}
