apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-connection
data:
  RABBITMQ_HOST: {{ .Values.global.rabbitmq.host | quote }}
  RABBITMQ_PORT: {{ .Values.global.rabbitmq.port | quote }}
  RABBITMQ_USERNAME: {{ .Values.global.rabbitmq.username | quote }}