apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Values.name }}
    component: api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector:
    app: {{ .Values.name }}